include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true