name: velin
description: "A free, open-source PDF application built with Flutter."

publish_to: 'none'

version: 0.5.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  material_ui: ^1.4.0
  go_router: ^18.0.1
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  get_it: ^9.3.0
  window_manager: ^0.5.2
  file_picker: ^13.1.0
  uuid: ^4.6.0
  pdfrx: ^2.6.5
  material_symbols_icons: ^4.2960.0
  pdfrx_engine: ^0.6.1
  image: ^4.10.1
  pdf_cos: ^6.0.0
  crypto: ^3.0.7
  pdf_manipulator: ^5.0.1
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  path_provider: ^2.1.6
  path: ^1.9.1
  flutter_svg: ^2.3.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_lint: ^0.4.3
  bloc_test: ^10.0.0
  build_runner: ^2.16.1
  mocktail: ^1.0.5
  drift_dev: ^2.35.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/icon_mono.svg

hooks:
  user_defines:
    pdf_manipulator:
      version: ^5.0.1
      keep: auto