// Mocks generated by Mockito from annotations
// in velin/test/app/shell/widgets/velin_window_controls_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i5;
import 'dart:ui' as _i2;

import 'package:flutter/material.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:window_manager/src/resize_edge.dart' as _i10;
import 'package:window_manager/src/title_bar_style.dart' as _i9;
import 'package:window_manager/src/window_listener.dart' as _i4;
import 'package:window_manager/src/window_manager.dart' as _i3;
import 'package:window_manager/src/window_options.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRect_0 extends _i1.SmartFake implements _i2.Rect {
  _FakeRect_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSize_1 extends _i1.SmartFake implements _i2.Size {
  _FakeSize_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffset_2 extends _i1.SmartFake implements _i2.Offset {
  _FakeOffset_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WindowManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockWindowManager extends _i1.Mock implements _i3.WindowManager {
  @override
  List<_i4.WindowListener> get listeners => (super.noSuchMethod(
    Invocation.getter(#listeners),
    returnValue: <_i4.WindowListener>[],
    returnValueForMissingStub: <_i4.WindowListener>[],
  ) as List<_i4.WindowListener>);

  @override
  bool get hasListeners => (super.noSuchMethod(
    Invocation.getter(#hasListeners),
    returnValue: false,
    returnValueForMissingStub: false,
  ) as bool);

  @override
  void addListener(_i4.WindowListener? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.WindowListener? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  double getDevicePixelRatio() => (super.noSuchMethod(
    Invocation.method(#getDevicePixelRatio, []),
    returnValue: 0.0,
    returnValueForMissingStub: 0.0,
  ) as double);

  @override
  _i5.Future<void> ensureInitialized() => (super.noSuchMethod(
    Invocation.method(#ensureInitialized, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<int> getId() => (super.noSuchMethod(
    Invocation.method(#getId, []),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  _i5.Future<void> setAsFrameless() => (super.noSuchMethod(
    Invocation.method(#setAsFrameless, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> waitUntilReadyToShow([
    _i6.WindowOptions? options,
    _i2.VoidCallback? callback,
  ]) => (super.noSuchMethod(
    Invocation.method(#waitUntilReadyToShow, [options, callback]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> destroy() => (super.noSuchMethod(
    Invocation.method(#destroy, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isPreventClose() => (super.noSuchMethod(
    Invocation.method(#isPreventClose, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setPreventClose(bool? isPreventClose) => (super.noSuchMethod(
    Invocation.method(#setPreventClose, [isPreventClose]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> focus() => (super.noSuchMethod(
    Invocation.method(#focus, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> blur() => (super.noSuchMethod(
    Invocation.method(#blur, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isFocused() => (super.noSuchMethod(
    Invocation.method(#isFocused, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> show({bool? inactive = false}) => (super.noSuchMethod(
    Invocation.method(#show, [], {#inactive: inactive}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> hide() => (super.noSuchMethod(
    Invocation.method(#hide, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isVisible() => (super.noSuchMethod(
    Invocation.method(#isVisible, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isMaximized() => (super.noSuchMethod(
    Invocation.method(#isMaximized, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> maximize({bool? vertically = false}) => (super.noSuchMethod(
    Invocation.method(#maximize, [], {#vertically: vertically}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> unmaximize() => (super.noSuchMethod(
    Invocation.method(#unmaximize, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isMinimized() => (super.noSuchMethod(
    Invocation.method(#isMinimized, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> minimize() => (super.noSuchMethod(
    Invocation.method(#minimize, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> restore() => (super.noSuchMethod(
    Invocation.method(#restore, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isFullScreen() => (super.noSuchMethod(
    Invocation.method(#isFullScreen, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setFullScreen(bool? isFullScreen) => (super.noSuchMethod(
    Invocation.method(#setFullScreen, [isFullScreen]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isDockable() => (super.noSuchMethod(
    Invocation.method(#isDockable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<_i3.DockSide?> isDocked() => (super.noSuchMethod(
    Invocation.method(#isDocked, []),
    returnValue: _i5.Future<_i3.DockSide?>.value(),
    returnValueForMissingStub: _i5.Future<_i3.DockSide?>.value(),
  ) as _i5.Future<_i3.DockSide?>);

  @override
  _i5.Future<void> dock({required _i3.DockSide? side, required int? width}) =>
      (super.noSuchMethod(
        Invocation.method(#dock, [], {#side: side, #width: width}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> undock() => (super.noSuchMethod(
    Invocation.method(#undock, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setAspectRatio(double? aspectRatio) => (super.noSuchMethod(
    Invocation.method(#setAspectRatio, [aspectRatio]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setBackgroundColor(_i2.Color? backgroundColor) =>
      (super.noSuchMethod(
        Invocation.method(#setBackgroundColor, [backgroundColor]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setAlignment(
    _i7.Alignment? alignment, {
    bool? animate = false,
  }) => (super.noSuchMethod(
    Invocation.method(#setAlignment, [alignment], {#animate: animate}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> center({bool? animate = false}) => (super.noSuchMethod(
    Invocation.method(#center, [], {#animate: animate}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Rect> getBounds() => (super.noSuchMethod(
    Invocation.method(#getBounds, []),
    returnValue: _i5.Future<_i2.Rect>.value(
      _FakeRect_0(this, Invocation.method(#getBounds, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i2.Rect>.value(
      _FakeRect_0(this, Invocation.method(#getBounds, [])),
    ),
  ) as _i5.Future<_i2.Rect>);

  @override
  _i5.Future<void> setBounds(
    _i2.Rect? bounds, {
    _i2.Offset? position,
    _i2.Size? size,
    bool? animate = false,
  }) => (super.noSuchMethod(
    Invocation.method(
      #setBounds,
      [bounds],
      {#position: position, #size: size, #animate: animate},
    ),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Size> getSize() => (super.noSuchMethod(
    Invocation.method(#getSize, []),
    returnValue: _i5.Future<_i2.Size>.value(
      _FakeSize_1(this, Invocation.method(#getSize, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i2.Size>.value(
      _FakeSize_1(this, Invocation.method(#getSize, [])),
    ),
  ) as _i5.Future<_i2.Size>);

  @override
  _i5.Future<void> setSize(_i2.Size? size, {bool? animate = false}) =>
      (super.noSuchMethod(
        Invocation.method(#setSize, [size], {#animate: animate}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Offset> getPosition() => (super.noSuchMethod(
    Invocation.method(#getPosition, []),
    returnValue: _i5.Future<_i2.Offset>.value(
      _FakeOffset_2(this, Invocation.method(#getPosition, [])),
    ),
    returnValueForMissingStub: _i5.Future<_i2.Offset>.value(
      _FakeOffset_2(this, Invocation.method(#getPosition, [])),
    ),
  ) as _i5.Future<_i2.Offset>);

  @override
  _i5.Future<void> setPosition(_i2.Offset? position, {bool? animate = false}) =>
      (super.noSuchMethod(
        Invocation.method(#setPosition, [position], {#animate: animate}),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMinimumSize(_i2.Size? size) => (super.noSuchMethod(
    Invocation.method(#setMinimumSize, [size]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setMaximumSize(_i2.Size? size) => (super.noSuchMethod(
    Invocation.method(#setMaximumSize, [size]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isResizable() => (super.noSuchMethod(
    Invocation.method(#isResizable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setResizable(bool? isResizable) => (super.noSuchMethod(
    Invocation.method(#setResizable, [isResizable]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isMovable() => (super.noSuchMethod(
    Invocation.method(#isMovable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setMovable(bool? isMovable) => (super.noSuchMethod(
    Invocation.method(#setMovable, [isMovable]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isMinimizable() => (super.noSuchMethod(
    Invocation.method(#isMinimizable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setMinimizable(bool? isMinimizable) => (super.noSuchMethod(
    Invocation.method(#setMinimizable, [isMinimizable]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isClosable() => (super.noSuchMethod(
    Invocation.method(#isClosable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isMaximizable() => (super.noSuchMethod(
    Invocation.method(#isMaximizable, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setMaximizable(bool? isMaximizable) => (super.noSuchMethod(
    Invocation.method(#setMaximizable, [isMaximizable]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setClosable(bool? isClosable) => (super.noSuchMethod(
    Invocation.method(#setClosable, [isClosable]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isAlwaysOnTop() => (super.noSuchMethod(
    Invocation.method(#isAlwaysOnTop, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setAlwaysOnTop(bool? isAlwaysOnTop) => (super.noSuchMethod(
    Invocation.method(#setAlwaysOnTop, [isAlwaysOnTop]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isAlwaysOnBottom() => (super.noSuchMethod(
    Invocation.method(#isAlwaysOnBottom, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setAlwaysOnBottom(bool? isAlwaysOnBottom) =>
      (super.noSuchMethod(
        Invocation.method(#setAlwaysOnBottom, [isAlwaysOnBottom]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getTitle() => (super.noSuchMethod(
    Invocation.method(#getTitle, []),
    returnValue: _i5.Future<String>.value(
      _i8.dummyValue<String>(this, Invocation.method(#getTitle, [])),
    ),
    returnValueForMissingStub: _i5.Future<String>.value(
      _i8.dummyValue<String>(this, Invocation.method(#getTitle, [])),
    ),
  ) as _i5.Future<String>);

  @override
  _i5.Future<void> setTitle(String? title) => (super.noSuchMethod(
    Invocation.method(#setTitle, [title]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setTitleBarStyle(
    _i9.TitleBarStyle? titleBarStyle, {
    bool? windowButtonVisibility = true,
  }) => (super.noSuchMethod(
    Invocation.method(
      #setTitleBarStyle,
      [titleBarStyle],
      {#windowButtonVisibility: windowButtonVisibility},
    ),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<int> getTitleBarHeight() => (super.noSuchMethod(
    Invocation.method(#getTitleBarHeight, []),
    returnValue: _i5.Future<int>.value(0),
    returnValueForMissingStub: _i5.Future<int>.value(0),
  ) as _i5.Future<int>);

  @override
  _i5.Future<bool> isSkipTaskbar() => (super.noSuchMethod(
    Invocation.method(#isSkipTaskbar, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setSkipTaskbar(bool? isSkipTaskbar) => (super.noSuchMethod(
    Invocation.method(#setSkipTaskbar, [isSkipTaskbar]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setProgressBar(double? progress) => (super.noSuchMethod(
    Invocation.method(#setProgressBar, [progress]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setIcon(String? iconPath) => (super.noSuchMethod(
    Invocation.method(#setIcon, [iconPath]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> isVisibleOnAllWorkspaces() => (super.noSuchMethod(
    Invocation.method(#isVisibleOnAllWorkspaces, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setVisibleOnAllWorkspaces(
    bool? visible, {
    bool? visibleOnFullScreen,
  }) => (super.noSuchMethod(
    Invocation.method(
      #setVisibleOnAllWorkspaces,
      [visible],
      {#visibleOnFullScreen: visibleOnFullScreen},
    ),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setBadgeLabel([String? label]) => (super.noSuchMethod(
    Invocation.method(#setBadgeLabel, [label]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasShadow() => (super.noSuchMethod(
    Invocation.method(#hasShadow, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<void> setHasShadow(bool? hasShadow) => (super.noSuchMethod(
    Invocation.method(#setHasShadow, [hasShadow]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<double> getOpacity() => (super.noSuchMethod(
    Invocation.method(#getOpacity, []),
    returnValue: _i5.Future<double>.value(0.0),
    returnValueForMissingStub: _i5.Future<double>.value(0.0),
  ) as _i5.Future<double>);

  @override
  _i5.Future<void> setOpacity(double? opacity) => (super.noSuchMethod(
    Invocation.method(#setOpacity, [opacity]),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> setBrightness(_i2.Brightness? brightness) =>
      (super.noSuchMethod(
        Invocation.method(#setBrightness, [brightness]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> setIgnoreMouseEvents(
    bool? ignore, {
    bool? forward = false,
  }) => (super.noSuchMethod(
    Invocation.method(#setIgnoreMouseEvents, [ignore], {#forward: forward}),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> popUpWindowMenu() => (super.noSuchMethod(
    Invocation.method(#popUpWindowMenu, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> startDragging() => (super.noSuchMethod(
    Invocation.method(#startDragging, []),
    returnValue: _i5.Future<void>.value(),
    returnValueForMissingStub: _i5.Future<void>.value(),
  ) as _i5.Future<void>);

  @override
  _i5.Future<void> startResizing(_i10.ResizeEdge? resizeEdge) =>
      (super.noSuchMethod(
        Invocation.method(#startResizing, [resizeEdge]),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> grabKeyboard() => (super.noSuchMethod(
    Invocation.method(#grabKeyboard, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> ungrabKeyboard() => (super.noSuchMethod(
    Invocation.method(#ungrabKeyboard, []),
    returnValue: _i5.Future<bool>.value(false),
    returnValueForMissingStub: _i5.Future<bool>.value(false),
  ) as _i5.Future<bool>);
}
