import {
  ExternalLink,
  FilePlus,
  Image,
  Lock,
  Minimize2,
  PlusSquare,
  RotateCw,
  Scissors,
  Type,
  Unlock,
} from "lucide-react";
import { ToolInfo } from "./tool";

export const TOOLS: ToolInfo[] = [
  {
    id: "merge",
    title: "Merge PDF",
    description: "Combine multiple PDFs into a single document.",
    icon: PlusSquare,
    color: "blue",
    category: "edit",
  },
  {
    id: "split",
    title: "Split PDF",
    description: "Separate a PDF into multiple files by page range.",
    icon: Scissors,
    color: "red",
    category: "edit",
  },
  {
    id: "extract",
    title: "Extract Pages",
    description: "Save specific pages as a new PDF file.",
    icon: ExternalLink,
    color: "grape",
    category: "edit",
  },
  {
    id: "compress",
    title: "Compress PDF",
    description: "Reduce file size without losing quality.",
    icon: Minimize2,
    color: "green",
    category: "optimize",
  },
  {
    id: "pdf-to-image",
    title: "PDF to Image",
    description: "Convert PDF pages into high-quality images.",
    icon: Image,
    color: "orange",
    category: "convert",
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    description: "Create a PDF from a collection of images.",
    icon: FilePlus,
    color: "cyan",
    category: "convert",
  },
  {
    id: "rotate",
    title: "Rotate PDF",
    description: "Change the orientation of your PDF pages.",
    icon: RotateCw,
    color: "indigo",
    category: "edit",
  },
  {
    id: "protect",
    title: "Protect PDF",
    description: "Add a password and secure your document.",
    icon: Lock,
    color: "pink",
    category: "security",
  },
  {
    id: "unlock",
    title: "Unlock PDF",
    description: "Remove password protection from your PDF.",
    icon: Unlock,
    color: "violet",
    category: "security",
  },
  {
    id: "watermark",
    title: "Watermark",
    description: "Add text or image watermarks to your PDF.",
    icon: Type,
    color: "yellow",
    category: "edit",
  },
];

export const CATEGORIES = [
  { label: "All", value: "all" },
  { label: "Edit", value: "edit" },
  { label: "Convert", value: "convert" },
  { label: "Optimize", value: "optimize" },
  { label: "Security", value: "security" },
] as const;
